services:
  db:
    image: mysql:8.0
    volumes:
      - ./my.cnf:/etc/mysql/my.cnf
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=${DATABASE}
      - MYSQL_ROOT_PASSWORD=${DBPASSWORD}

  web:
    image: dunglas/frankenphp
    depends_on:
      - db
    volumes:
      - ./:/app/public
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    entrypoint: ["/bin/sh","-c"]
    environment:
      - DATABASE_HOSTNAME=db
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=${DBPASSWORD}
      - DATABASE_DATABASE=${DATABASE}
    command:
      - |
        install-php-extensions pdo_mysql
        frankenphp run --config /etc/caddy/Caddyfile
