services:
  db:
    image: mariadb
    environment:
      - MARIADB_USER=${DBUSER}
      - MARIADB_PASSWORD=${DBPASSWORD}
      - MARIADB_DATABASE=${DATABASE}
      - MARIADB_RANDOM_ROOT_PASSWORD=1

  web:
    image: dunglas/frankenphp
    depends_on:
      - db
    volumes:
      - ./:/app/public
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    entrypoint: ["/bin/sh","-c"]
    environment:
      - DATABASE_HOSTNAME=db
      - DATABASE_USERNAME=${DBUSER}
      - DATABASE_PASSWORD=${DBPASSWORD}
      - DATABASE_DATABASE=${DATABASE}
    tty: true
    command:
      - |
        install-php-extensions mysqli
        frankenphp run --config /etc/caddy/Caddyfile
