name: Negative test

on:
  push:

env:
    DBPASSWORD: bar
    DATABASE: baz

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: docker compose up --no-deps web --detach --wait
      env:
        DBPASSWORD: ${{ env.DBPASSWORD }}
        DATABASE: ${{ env.DATABASE }}
    - run: curl -visk https://localhost
    - run: docker compose logs