name: Negative test, no db service

on:
  push:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # don't bring up the db service
      - run: docker compose up --no-deps --detach --wait web
      - uses: "ramsey/composer-install@v3"
      - run: test $(curl -sk -o /dev/null -w "%{http_code}" https://localhost/negative/) -eq 500
      - run: docker compose logs
