name: Docker Compose and Smoke Test

on:
  push:
    branches:
      - main

env:
    DBPASSWORD: bar
    DATABASE: baz

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: docker compose up --wait --detach --quiet-pull
      env:
        DBPASSWORD: ${{ env.DBPASSWORD }}
        DATABASE: ${{ env.DATABASE }}
    - uses: "ramsey/composer-install@v3"
    - run: curl -isf https://localhost/positive/
    - run: docker compose logs
      if: ${{ always() }}
