name: Docker Compose and Smoke Test

on:
  push:
    branches:
      - main

env:
    DBUSER: foo
    DBPASSWORD: bar
    DATABASE: baz

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: docker compose up --wait --detach --quiet-pull
      env:
        DBUSER: ${{ env.DBUSER }}
        DBPASSWORD: ${{ env.DBPASSWORD }}
        DATABASE: ${{ env.DATABASE }}
    - run: curl -k -f https://localhost